# Generated by Django 2.2 on 2019-05-16 21:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterclone', '0004_notification_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 16, 21, 4, 10, 877033)),
        ),
    ]
